theme = "arrebol"


[keys.normal]
C-s = ":w"
C-p = "command_palette"
q = ":q"

[keys.insert]
C-p = "command_palette"

[keys.select]
C-p = "command_palette"

[editor]
cursorline = true
auto-save = true
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"


[editor.statusline]
left = ["mode", "version-control", "file-name","position", "file-modification-indicator", "diagnostics" ]
center = ["spinner"]
right = ["selections", "position-percentage", "file-encoding", "file-type", "mode"]


[editor.lsp]
display-messages= true
display-inlay-hints = true


[editor.indent-guides]
render = true
skip-levels = 2
character = "▏"

[editor.whitespace.characters]
newline = "⏎"
tab = "→"
