theme = "sky-light"


[keys.normal]
C-s = ":w"
C-p = "command_palette"

[keys.insert]
C-p = "command_palette"

[keys.select]
C-p = "command_palette"

[editor]
cursorline = true
auto-save = true
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"


[editor.statusline]
left = ["mode", "file-name" ]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type", "mode"]


[editor.lsp]
display-messages= true
# display-inlay-hints = true


[editor.indent-guides]
render = true
skip-levels = 1

[editor.whitespace.characters]
newline = "⏎"
tab = "→"